### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_installed_distributions'

### ISSUE THREAD

**Issue by eschava** [domogik/domogik-mq#6]
Cannot install domogik-mq using  sudo ./install.py --dist-packages
Error is:

```
 [ Run setup.py ]
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    for mod in pip.get_installed_distributions():
AttributeError: 'module' object has no attribute 'get_installed_distributions'
========= TRACEBACK =============
Traceback (most recent call last):
  File "./install.py", line 332, in install
    raise OSError("setup.py doesn't finish correctly")
OSError: setup.py doesn't finish correctly

```

**Comment by eschava** [comment]
Suggestion from https://github.com/Miserlou/Zappa/issues/1471#issuecomment-412603196 helped
I've replaced

`for mod in pip.get_installed_distributions():`

with
```
if pip.__version__ >= "10.0.0":
    from pip._internal.utils.misc import get_installed_distributions
else:
    from pip import get_installed_distributions

for mod in get_installed_distributions():

```

**Comment by eschava** [comment]
same for setup.py and common/database.py in domogik main package
